import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
export function createHeater(canvas){
 const renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0,0);renderer.toneMapping=T.ACESFilmicToneMapping;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(35,1,.1,100),root=new T.Group();scene.add(root);const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromScene(new RoomEnvironment(),.04).texture;
 const grey=new T.MeshStandardMaterial({color:0x515253,metalness:.08,roughness:.62}),black=new T.MeshStandardMaterial({color:0x090a0b,roughness:.4}),silver=new T.MeshStandardMaterial({color:0x999999,metalness:.85,roughness:.25}),wood=new T.MeshStandardMaterial({color:0x30211a,roughness:.65});
 function box(w,h,d,r,mat,parent,x=0,y=0,z=0){r=Math.min(r,w/2-.001,h/2-.001);const shape=new T.Shape(),a=-w/2,b=-h/2;shape.moveTo(a+r,b);shape.lineTo(a+w-r,b);shape.quadraticCurveTo(a+w,b,a+w,b+r);shape.lineTo(a+w,b+h-r);shape.quadraticCurveTo(a+w,b+h,a+w-r,b+h);shape.lineTo(a+r,b+h);shape.quadraticCurveTo(a,b+h,a,b+h-r);shape.lineTo(a,b+r);shape.quadraticCurveTo(a,b,a+r,b);const g=new T.ExtrudeGeometry(shape,{depth:d,bevelEnabled:false,curveSegments:16});g.translate(0,0,-d/2);const m=new T.Mesh(g,mat);m.position.set(x,y,z);parent.add(m);return m}

 function label(text,w,h,color='#fff',bg=null){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d');if(bg){x.fillStyle=bg;x.fillRect(0,0,512,256)}x.fillStyle=color;x.textAlign='center';x.textBaseline='middle';x.font='bold 85px Arial';x.fillText(text,256,128);const tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;return new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:tx,transparent:true,depthWrite:false}))}
 let imported=null,parts=[],loadError=null;
 const loader=new GLTFLoader();const ready=loader.loadAsync('/products/RE-7-122/assets/REBUNE_Heater.glb').then(gltf=>{
 imported=gltf.scene;const bounds=new T.Box3().setFromObject(imported),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3());const scale=4/size.y;
 imported.scale.setScalar(scale);imported.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);root.add(imported);
 imported.traverse(o=>{if(!o.isMesh)return;const n=o.name.toLowerCase();let axis=null;if(n.includes('front')||n.includes('control')||n.includes('fire_window')||n.includes('fire window')||n.includes('charred')||n.includes('flame')||['33','p','t','+','-'].includes(n))axis=new T.Vector3(0,0,.065);else if(n.includes('leg')||n.includes('foot'))axis=new T.Vector3(0,-.026,0);else if(n.includes('top'))axis=new T.Vector3(0,.055,0);else if(n.includes('rear')||n.includes('power contact'))axis=new T.Vector3(0,0,-.04);if(axis)parts.push({object:o,origin:o.position.clone(),axis});});
 return imported;
 }).catch(error=>{loadError=error;throw error});
 const key=new T.DirectionalLight(0xfff4e8,3.5);key.position.set(3,5,5);scene.add(key);const rim=new T.DirectionalLight(0x94b6db,2.5);rim.position.set(-3,4,-2);scene.add(rim);const warm=new T.PointLight(0xff691e,4,10);warm.position.set(0,2.5,2);scene.add(warm);
 const remote=new T.Group();scene.add(remote);box(.64,1.4,.12,.1,black,remote);const white=new T.MeshStandardMaterial({color:0xe8e6e2,roughness:.4});box(.60,1.35,.025,.09,white,remote,0,0,.069);
 const names=['On/Standby','Cool','Timer','Temp','Flame','Mist'];const icons=['⏻','Ⅲ','◷','♙','♨','♧'];
 for(let i=0;i<6;i++){const x=i%2===0?-.16:.16,y=.47-Math.floor(i/2)*.34;const button=new T.Mesh(new T.CylinderGeometry(.083,.083,.015,32),i===0?new T.MeshStandardMaterial({color:0xdd191b}):white);button.rotation.x=Math.PI/2;button.position.set(x,y,.09);remote.add(button);const ring=new T.Mesh(new T.TorusGeometry(.083,.004,6,32),black);ring.position.set(x,y,.102);remote.add(ring);const icon=label(icons[i],.11,.10,'#111');icon.position.set(x,y,.11);remote.add(icon);const text=label(names[i],.26,.062,'#111');text.position.set(x,y-.12,.103);remote.add(text)}
 const remoteLogo=label('REBUNE',.4,.1,'#222');remoteLogo.position.set(0,-.52,.103);remote.add(remoteLogo);box(.45,.5,.015,.03,black,remote,0,-.3,-.067);
 const frames=[[-.55,2.2,8.5,2.1], [.5,2.8,7.6,2.15], [.14,2.85,4.1,2.62],[-.35,3.1,5.6,2.55],[.22,2.8,7.1,2.5],[-.55,4.6,5.2,3.1],[.5,3.1,9.7,2.1],[.35,2.7,8.6,2.05]];
 let progress=0,reduce=false,dead=false;function render(time){if(dead||!canvas.clientWidth||!canvas.clientHeight)return;const a=Math.floor(progress),b=Math.min(7,a+1),t=progress-a,u=t*t*(3-2*t),f=frames[a].map((v,i)=>T.MathUtils.lerp(v,frames[b][i],u));root.rotation.y=f[0]+(progress>6.7&&!reduce?Math.sin(time*.0004)*.015:0);if(progress>2.8&&progress<3.8)root.rotation.y+=Math.sin((progress-2.8)*Math.PI)*1.35;
 const remoteAmount=Math.max(0,1-Math.abs(progress-4)/.8);remote.visible=remoteAmount>0;remote.position.set(-1.05,2.65,.8+remoteAmount*.65);remote.rotation.set(-.06,-.18+(1-remoteAmount)*.9,-.1);remote.scale.setScalar(.35+remoteAmount*.65);
 const ex=Math.max(0,1-Math.abs(progress-6)/.38);for(const part of parts)part.object.position.copy(part.origin).addScaledVector(part.axis,ex);
 camera.position.set(.15,f[1],f[2]+(canvas.clientWidth/canvas.clientHeight<.8?2:0));camera.lookAt(0,f[3],0);key.intensity=.7+Math.min(progress,1)*3;key.position.x=3+Math.sin(progress*2)*3;warm.intensity=progress>1.3&&progress<3?5:1;
 const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*renderer.getPixelRatio())||canvas.height!==Math.round(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}renderer.render(scene,camera)}renderer.setAnimationLoop(t=>{if(!document.hidden)render(t)});addEventListener('pagehide',()=>{dead=true;renderer.setAnimationLoop(null);renderer.dispose();pm.dispose()},{once:true});return {ready,update(p,r){progress=p;reduce=r}};
}
